scalar DateTime

input DateRangeInput {
  from: DateTime!
  to: DateTime!
}

input AbastecimentoFiltersInput {
  dateRange: DateRangeInput
  fuelType: [String!]
  vehiclePlate: String
  driverName: String
  department: [String!]     # ou String, se quiser só um valor
  vehicleModel: [String]
  gasStationCity: [String]
  gasStationName: [String]
}

type Vehicle {
  plate: String
  model: String
  brand: String
}

type GasStation {
  name: String
  city: String
}

type Abastecimento {
  id: ID!
  datetime: DateTime
  cost: Float
  fuelVolume: Float
  fuelType: String
  driverName: String
  vehicle: Vehicle
  gasStation: GasStation
  department: String
  costCenter: String
}

type AbastecimentoColumn {
  headerLabel: String!
  accessor: String!
  isSortable: Boolean!
  dataType: String!
}

type AbastecimentoKpis {
  totalCost: Float!
  fuelConsumed: Float!  
  kilometersDriven: Float! 
  vehiclesCount: Int! 
  dailyAverageCost: Float!
  suppliesCount: Int!
  lastUpdate: DateTime!
}

type FilterOption {
  value: String
  label: String
}

type CostByVehicle {
  vehicle: String!
  total: Float!
}

type CostByDepartment {
  department: String!
  total: Float!
}

type CostByCity {
  city: String!
  total: Float!
}

type CostByGasStation {
  name: String!
  total: Float!
}

type CostByPlate {
  plate: String!
  total: Float!
}

type CostByDate {
  date: String! # yyyy-mm-dd
  total: Float!
}

type CostOverTime {
  date: String! # yyyy-mm-dd
  total: Float!
}

type RankingByDate {
  date: String! # yyyy-mm-dd
  total: Float!
}

type RankingByPlate {
  plate: String!
  total: Float!
  quantity: Int!
}

type RankingByDepartment {
  department: String!
  total: Float!
}

type Query {
  abastecimentos(
    limit: Int
    offset: Int
    sortBy: String
    sortDirection: String
    filters: AbastecimentoFiltersInput
  ): [Abastecimento!]!

  abastecimentosCount(filters: AbastecimentoFiltersInput): Int!
  abastecimentoKpis(filters: AbastecimentoFiltersInput): AbastecimentoKpis!

  departmentOptions: [FilterOption]
  vehiclePlateOptions: [FilterOption]
  vehicleModelOptions: [FilterOption]
  gasStationCityOptions: [FilterOption]
  gasStationNameOptions: [FilterOption]

  costByVehicle(filters: AbastecimentoFiltersInput): [CostByVehicle!]!
  costByDepartment(filters: AbastecimentoFiltersInput): [CostByDepartment!]!
  costByCity(filters: AbastecimentoFiltersInput): [CostByCity!]!
  costByGasStation(filters: AbastecimentoFiltersInput): [CostByGasStation!]!
  costByPlate(filters: AbastecimentoFiltersInput): [CostByPlate!]!
  costByDate(filters: AbastecimentoFiltersInput): [CostByDate!]!
  costOverTime(filters: AbastecimentoFiltersInput): [CostOverTime!]!

  rankingByDate(filters: AbastecimentoFiltersInput): [RankingByDate!]!
  rankingByPlate(filters: AbastecimentoFiltersInput): [RankingByPlate!]!
  rankingByDepartment(filters: AbastecimentoFiltersInput): [RankingByDepartment!]!

  abastecimentosColumns: [AbastecimentoColumn!]!
}
